[toolchain]

[features]
resolvable = true
skip-lint = false

[programs.localnet]
alloc_spike = "ApAD9vA6UX8F31AYjCE36a3w3iVFR4ujM9Xo2o97PwQj"
onelayer_registry = "6A2LSwaJKdwVAEggAfHjZVAKb2ATWM7AXBrgDEqczEo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
