import assert from 'node:assert/strict';
import test from 'node:test';
import { generateKeyPairSync, sign, randomUUID } from 'node:crypto';
import { isolatedPostgres } from './support/postgres.ts';
import { routeWorkflow, workflowHash, ingestWorkflowSource, sourceSigningBytes, type WorkflowSourceEvent } from '../src/registry-workflow.ts';
import type { AdminSession } from '../src/admin-session.ts';

const session = (username: string): AdminSession => ({username,sessionId:username,role:'operator',csrfToken:'synthetic',expiresAt:Date.now()+60000,permissions:['records.read','records.draft','records.approve'],registryIds:['synthetic'],resourcePolicy:{version:1,grants:[{registryId:'synthetic',recordIds:'all',fieldPaths:'all',actions:['records.read','records.write']}]}});
test('workflow binds independent approval, concurrency and atomic immutable publication', {timeout:60000}, async t => {
  const {pool}=await isolatedPostgres(t);
  const call=async (who:string,path:string,body:Record<string,unknown>,key=randomUUID())=>routeWorkflow({pool,registryId:'synthetic'},{method:'POST',path:'/v2/admin/workflow/drafts'+path,body,idempotencyKey:key},session(who));
  const create=async (recordId:string)=>{ const r=await call('alice','',{recordId,baseVersion:0,operation:'upsert',payload:{owner:'Synthetic'}}); assert.equal(r.status,201); return r.body as any; };
  const act=async (who:string,d:any,action:string,extra={})=>call(who,`/${d.draftId}/${action}`,{expectedRevision:d.revision,payloadHash:d.payloadHash,baseVersion:d.baseVersion,...extra});
  let d=await create('record');
  assert.equal((await act('alice',d,'submit')).status,200);
  assert.equal((await act('alice',d,'approve')).status,403);
  assert.equal((await act('bob',d,'approve',{payloadHash:'0'.repeat(64)})).status,409);
  assert.equal((await act('bob',d,'approve')).status,200);
  const edits=await Promise.all([act('alice',d,'edit',{operation:'upsert',payload:{owner:'changed'}}),act('carol',d,'edit',{operation:'upsert',payload:{owner:'other'}})]);
  assert.deepEqual(edits.map(r=>r.status).sort(),[200,409]);
  d=edits.find(r=>r.status===200)!.body;
  assert.equal(d.state,'DRAFT');
  assert.equal((await act('alice',d,'commit')).status,409);
  assert.equal((await act('alice',d,'submit')).status,200);
  assert.equal((await act('bob',d,'approve')).status,200);
  const second=await create('record');
  await act('alice',second,'submit'); await act('bob',second,'approve');
  // Force an outbox insert failure after version allocation: every write rolls back.
  await pool.query("CREATE FUNCTION synthetic_outbox_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic outbox crash'; END $$; CREATE TRIGGER synthetic_failure BEFORE INSERT ON wf_outbox FOR EACH ROW EXECUTE FUNCTION synthetic_outbox_failure()");
  const before=(await pool.query('SELECT count(*) FROM wf_audit')).rows[0].count;
  await assert.rejects(act('alice',d,'commit'),/synthetic outbox crash/);
  assert.equal((await pool.query('SELECT count(*) FROM wf_version')).rows[0].count,'0');
  assert.equal((await pool.query('SELECT count(*) FROM wf_record')).rows[0].count,'0');
  assert.equal((await pool.query('SELECT count(*) FROM wf_audit')).rows[0].count,before);
  await pool.query('DROP TRIGGER synthetic_failure ON wf_outbox');
  const commits=await Promise.all([act('alice',d,'commit'),act('alice',second,'commit')]);
  assert.deepEqual(commits.map(r=>r.status).sort(),[200,409]);
  assert.equal((await pool.query('SELECT count(*) FROM wf_version')).rows[0].count,'1');
  assert.equal((await pool.query('SELECT count(*) FROM wf_outbox')).rows[0].count,'1');
  for(const table of ['wf_version','wf_outbox','wf_audit','wf_revision']) await assert.rejects(pool.query(`DELETE FROM ${table}`),/immutable/);
  const replayKey=randomUUID();
  const replayBody={recordId:'replay',baseVersion:0,operation:'upsert',payload:{secret:'synthetic'}};
  const original=await call('alice','',replayBody,replayKey);
  assert.deepEqual(await call('alice','',replayBody,replayKey),original);
  assert.equal((await call('alice','',{...replayBody,recordId:'different'},replayKey)).status,409);
  const denied=session('alice'); denied.resourcePolicy={version:1,grants:[]};
  assert.equal((await routeWorkflow({pool,registryId:'synthetic'},{method:'POST',path:'/v2/admin/workflow/drafts',body:replayBody,idempotencyKey:replayKey},denied)).status,403);
  const replayDraft=original.body as any;
  await act('alice',replayDraft,'edit',{operation:'upsert',payload:{}});
  const noFields=session('alice'); noFields.resourcePolicy={version:1,grants:[{registryId:'synthetic',recordIds:'all',fieldPaths:[],actions:['records.write']}]};
  assert.equal((await routeWorkflow({pool,registryId:'synthetic'},{method:'POST',path:'/v2/admin/workflow/drafts',body:replayBody,idempotencyKey:replayKey},noFields)).status,403);
  // Full replacement/tombstone must authorize fields removed from the existing version.
  const restricted=session('alice'); restricted.resourcePolicy={version:1,grants:[{registryId:'synthetic',recordIds:'all',fieldPaths:[],actions:['records.read','records.write']}]};
  const restrictedCall=(path:string,body:Record<string,unknown>)=>routeWorkflow({pool,registryId:'synthetic'},{method:'POST',path:'/v2/admin/workflow/drafts'+path,body,idempotencyKey:randomUUID()},restricted);
  for (const operation of ['upsert','tombstone']) assert.equal((await restrictedCall('',{recordId:'record',baseVersion:1,operation,payload:{}})).status,403);
  const replacement=await call('alice','',{recordId:'record',baseVersion:1,operation:'tombstone',payload:{}});
  const replacementDraft=replacement.body as any;
  await act('alice',replacementDraft,'submit'); await act('bob',replacementDraft,'approve');
  assert.equal((await restrictedCall(`/${replacementDraft.draftId}/commit`,{expectedRevision:1,payloadHash:replacementDraft.payloadHash,baseVersion:1})).status,403);
  assert.equal((await call('alice','',{recordId:'ambiguous',baseVersion:0,operation:'upsert',payload:{'a.b':'hidden'}})).status,400);
  const rejected=await create('rejected'); await act('alice',rejected,'submit');
  assert.equal((await act('bob',rejected,'reject')).status,200);
  assert.equal((await act('alice',rejected,'commit')).status,409);
});

test('signed source enforces three signatures, exact contiguous cursor, duplicates and tombstones', {timeout:60000}, async t=>{
  const {pool}=await isolatedPostgres(t);
  const source=generateKeyPairSync('ed25519'), alice=generateKeyPairSync('ed25519'), bob=generateKeyPairSync('ed25519');
  const trust={registryId:'synthetic',sourceId:'source',sourceKey:source.publicKey,people:new Map([['alice',{key:alice.publicKey,permissions:['draft'] as const}],['bob',{key:bob.publicKey,permissions:['approve'] as const}]])};
  const event:WorkflowSourceEvent={version:1,registryId:'synthetic',sourceId:'source',cursor:1,recordId:'sourced',baseVersion:0,operation:'upsert',payload:{owner:'synthetic'},payloadHash:workflowHash({operation:'upsert',payload:{owner:'synthetic'}}),creator:'alice',approver:'bob'};
  const envelope=(e:WorkflowSourceEvent)=>({event:e,sourceSignature:sign(null,sourceSigningBytes(e),source.privateKey).toString('base64url'),creatorSignature:sign(null,sourceSigningBytes(e),alice.privateKey).toString('base64url'),approverSignature:sign(null,sourceSigningBytes(e),bob.privateKey).toString('base64url')});
  const ingest=(e:WorkflowSourceEvent)=>ingestWorkflowSource(pool,trust,envelope(e));
  await assert.rejects(ingest({...event,cursor:2}),/SOURCE_CURSOR_GAP/);
  const signed=envelope(event); signed.approverSignature=signed.creatorSignature;
  await assert.rejects(ingestWorkflowSource(pool,trust,signed),/SOURCE_SIGNATURE/);
  await assert.rejects(ingest({...event,approver:'alice'}),/SELF_APPROVAL/);
  const aliasTrust={...trust,people:new Map([...trust.people, ['bob',{key:alice.publicKey,permissions:['approve'] as const}]])};
  await assert.rejects(ingestWorkflowSource(pool,aliasTrust,envelope(event)),/SELF_APPROVAL/);
  const first=await ingest(event); assert.deepEqual(await ingest(event),first);
  await assert.rejects(ingest({...event,recordId:'other'}),/SOURCE_EQUIVOCATION/);
  await assert.rejects(ingest({...event,cursor:2,operation:'delete' as any}),/INVALID_PAYLOAD/);
  const tombstone={...event,cursor:2,baseVersion:1,operation:'tombstone' as const,payload:{},payloadHash:workflowHash({operation:'tombstone',payload:{}})};
  assert.equal((await ingest(tombstone)).version,2);
  assert.deepEqual(await ingest(event),first);
  await assert.rejects(ingest({...tombstone,cursor:3,baseVersion:1}),/BASE_VERSION_CONFLICT/);
  assert.equal((await pool.query('SELECT cursor FROM wf_source_cursor')).rows[0].cursor,'2');
  assert.equal((await pool.query('SELECT count(*) FROM wf_outbox')).rows[0].count,'2');
  // Caller-owned objects can change while acquiring a connection. Persist only signed bytes.
  const mutable=envelope({...event,cursor:3,recordId:'immutable-input',payload:{owner:'synthetic'}});
  const pending=ingestWorkflowSource(pool,trust,mutable);
  mutable.event.payload.owner='unsigned mutation';
  mutable.event.recordId='unsigned-target';
  mutable.approverSignature='tampered';
  const accepted=await pending;
  assert.equal(accepted.recordId,'immutable-input');
  const stored=(await pool.query("SELECT payload,evidence FROM wf_version WHERE record_id='immutable-input'")).rows[0];
  assert.deepEqual(stored.payload,{owner:'synthetic'});
  assert.equal(stored.evidence.event.recordId,'immutable-input');
  assert.notEqual(stored.evidence.approverSignature,'tampered');
  const next={...event,cursor:4,recordId:'atomic-source'};
  const counts=async()=> (await pool.query('SELECT (SELECT count(*) FROM wf_version) AS versions,(SELECT count(*) FROM wf_outbox) AS outbox,(SELECT count(*) FROM wf_audit) AS audit,(SELECT count(*) FROM wf_source_event) AS events,(SELECT cursor FROM wf_source_cursor) AS cursor')).rows[0];
  const before=await counts();
  await pool.query("CREATE FUNCTION synthetic_source_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic cursor crash'; END $$; CREATE TRIGGER synthetic_failure BEFORE UPDATE ON wf_source_cursor FOR EACH ROW EXECUTE FUNCTION synthetic_source_failure()");
  await assert.rejects(ingest(next),/synthetic cursor crash/);
  assert.deepEqual(await counts(),before);
  assert.equal((await pool.query("SELECT count(*) FROM wf_record WHERE record_id='atomic-source'")).rows[0].count,'0');
  await pool.query('DROP TRIGGER synthetic_failure ON wf_source_cursor');
  const duplicates=await Promise.all([ingest(next),ingest(next)]);
  assert.deepEqual(duplicates[0],duplicates[1]);
  assert.equal((await counts()).events,'4');
  const revoked={...trust,people:new Map([...trust.people].filter(([name])=>name!=='bob'))};
  await assert.rejects(ingestWorkflowSource(pool,revoked,envelope(next)),/SOURCE_SIGNATURE/);

});
